kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-api-k8s
  labels:
    k8s-app: go-api-k8s
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: go-api-k8s
  template:
    metadata:
      name: go-api-k8s
      labels:
        k8s-app: go-api-k8s
        version: v1
    spec:
      containers:
        - name: go-api-k8s
          image: douglaszuqueto/go-api-k8s
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 200m
      restartPolicy: Always
