kind: Service
apiVersion: v1
metadata:
  name: go-api-k8s
  namespace: default
  labels:
    k8s-app: go-api-k8s
    version: v2
spec:
  ports:
    - name: tcp-5000-4000
      protocol: TCP
      port: 5000
      targetPort: 4000
  selector:
    k8s-app: go-api-k8s
    version: v2
  type: LoadBalancer
      